# #!/bin/bash
# # Author Andrew S via Upwork
# # License: GPLv3

ps -a
pidof openvpn | xargs kill 2>/dev/null
ps -a

IPRANGE=(AUMelbourne.ovpn AUPerth.ovpn AUSydney.ovpn Albania.ovpn Argentina.ovpn Austria.ovpn Belgium.ovpn Bulgaria.ovpn CAMontreal.ovpn CAOntario.ovpn CAToronto.ovpn CAVancouver.ovpn
CzechRepublic.ovpn DEBerlin.ovpn DEFrankfurt.ovpn Denmark.ovpn Estonia.ovpn Finland.ovpn France.ovpn
Greece.ovpn Hungary.ovpn Iceland.ovpn India.ovpn Ireland.ovpn Israel.ovpn Italy.ovpn Japan.ovpn Latvia.ovpn 
Lithuania.ovpn Luxembourg.ovpn Moldova.ovpn Netherlands.ovpn NewZealand.ovpn NorthMacedonia.ovpn Norway.ovpn 
Poland.ovpn Portugal.ovpn Romania.ovpn Serbia.ovpn Singapore.ovpn Slovakia.ovpn SouthAfrica.ovpn Spain.ovpn 
Sweden.ovpn Switzerland.ovpn Turkey.ovpn UAE.ovpn UKLondon.ovpn UKManchester.ovpn UKSouthampton.ovpn 
USAtlanta.ovpn USCalifornia.ovpn USChicago.ovpn USDallas.ovpn USDenver.ovpn USEast.ovpn USFlorida.ovpn 
USHouston.ovpn USLasVegas.ovpn USNewYorkCity.ovpn USSeattle.ovpn USSiliconValley.ovpn 
USWashingtonDC.ovpn USWest.ovpn Ukraine.ovpn
)

sleep 0.5

CHOICE=$(shuf -n1 -i 1-"${#IPRANGE[@]}")
REGION=""${IPRANGE[$CHOICE-1]}"" && echo $REGION

echo "Switching to $REGION"


> /etc/resolv.conf
tee -a << EOF > /etc/resolv.conf
# Generated by NetworkManager
search compute
nameserver 1.1.1.1
nameserver 8.8.8.8
EOF

restorecon -Rv /etc/openvpn/

IPADDR=($(hostname -I)) && echo $IPADDR
HOSTSUBNET=$(ip route | grep "$IPADDR" | awk -F" " '{ print $1 }') && echo $HOSTSUBNET
VIANET=$(ip route | grep via | grep -Eo -m1 '(via )([[:digit:]]{1,3}\.){3}([[:digit:]]{1,3})') && echo $VIANET

LINK=$(ip link | grep -Eo '(ens[[:digit:]]\:)')
if [[ $LINK = "" ]]; then
    LINK=$(ip link | grep -Eo '(eth[[:digit:]]\:)')
fi
echo $LINK

ip rule add from $IPADDR table 128
ip route add table 128 to $HOSTSUBNET dev ${LINK//:/}
ip route add table 128 default via ${VIANET//via/}
    
echo Wait...
nohup openvpn --config /etc/openvpn/$REGION &

# sleep 1

> /etc/resolv.conf
tee -a << EOF > /etc/resolv.conf
# Generated by NetworkManager
search compute
nameserver 1.1.1.1
nameserver 8.8.8.8
EOF

sleep 10

cat << EOF
Machine IP $IPADDR
New IP $(curl -s ipecho.net/plain)
Region: $REGION
EOF

