"""set nullable to author and remove atom_link

Revision ID: 1dfb169d1178
Revises: 36784f2d0fda
Create Date: 2020-07-17 13:05:10.764367

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1dfb169d1178'
down_revision = '36784f2d0fda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'author',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=True)
    op.drop_index('atom_link', table_name='articles')
    op.drop_column('articles', 'atom_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('atom_link', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=768), nullable=True))
    op.create_index('atom_link', 'articles', ['atom_link'], unique=True)
    op.alter_column('articles', 'author',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=False)
    # ### end Alembic commands ###
