"""change timestamp to datetime in publication_date in articles table

Revision ID: 831c95661443
Revises: 9417ac53e05d
Create Date: 2020-07-20 13:37:41.743731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '831c95661443'
down_revision = '9417ac53e05d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'publication_date', new_column_name='publication_date', type_=sa.DATETIME(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'publication_date', new_column_name='publication_date', type_=sa.TIMESTAMP(),
                    nullable=False)
    # ### end Alembic commands ###
