"""change categories type from varchar to text in articles table

Revision ID: 8e8f580dcd24
Revises: e1e5c916d642
Create Date: 2020-07-20 16:16:46.312632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e8f580dcd24'
down_revision = 'e1e5c916d642'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'categories', new_column_name='categories', type_=sa.TEXT())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'categories', new_column_name='categories', type_=sa.VARCHAR(length=768))
    # ### end Alembic commands ###
