"""remove unique index of guid in articles table

Revision ID: 9417ac53e05d
Revises: bec0fa513acd
Create Date: 2020-07-20 13:33:06.877347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9417ac53e05d'
down_revision = 'bec0fa513acd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('guid', table_name='articles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('guid', 'articles', ['guid'], unique=True)
    # ### end Alembic commands ###
