"""Add errr field to rewrite table

Revision ID: 99b6cb22a6fe
Revises: 4f582cdc8497
Create Date: 2020-07-27 11:24:32.660413

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '99b6cb22a6fe'
down_revision = '4f582cdc8497'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rewrites', sa.Column('error', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rewrites', 'error')
    # ### end Alembic commands ###
