"""remove unique index of text_filepath in articles table

Revision ID: bec0fa513acd
Revises: 78bf2982f37f
Create Date: 2020-07-20 13:31:55.749543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bec0fa513acd'
down_revision = '78bf2982f37f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('text_filepath', table_name='articles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('text_filepath', 'articles', ['text_filepath'], unique=True)
    # ### end Alembic commands ###
