"""change varchar length from 255 to 768 for categories in arctiles table

Revision ID: df147f7d8dc7
Revises: fb77b47e1ee6
Create Date: 2020-07-20 14:21:22.110832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df147f7d8dc7'
down_revision = 'fb77b47e1ee6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'categories', new_column_name='categories', type_=sa.VARCHAR(length=768))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'categories', new_column_name='categories', type_=sa.VARCHAR(length=255))
    # ### end Alembic commands ###
